# **Linear Regression by Normal Equation:**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
data = pd.read_csv("/content/drive/MyDrive/data/4K_House_Rent_Dataset.csv")
data.head()

Posted On  BHK   Rent  Size            Floor    Area Type  \
0  2022-05-18    2  10000  1100  Ground out of 2   Super Area   
1  2022-05-13    2  20000   800       1 out of 3   Super Area   
2  2022-05-16    2  17000  1000       1 out of 3   Super Area   
3  2022-07-04    2  10000   800       1 out of 2   Super Area   
4  2022-05-09    2   7500   850       1 out of 2  Carpet Area   

              Area Locality     City Furnishing Status  Tenant Preferred  \
0                    Bandel  Kolkata       Unfurnished  Bachelors/Family   
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family   
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family   
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family   
4             South Dum Dum  Kolkata       Unfurnished         Bachelors   

   Bathroom Point of Contact  
0         2    Contact Owner  
1         1    Contact Owner  
2         1    Contact Owner  
3         1    Contact Owner  
4         1    Contact Owner

In [3]:
data.shape

(4746, 12)

In [4]:
Y = data['Rent'].values
X1 = data['Size'].values
X2 = data['BHK'].values
X3 = data['City'].replace({'Bangalore':1,'Chennai':2,'Delhi':3,'Hyderabad':4,'Kolkata':5,'Mumbai':6})
X4 = data['Bathroom'].values
X5 = data["Furnishing Status"].replace({"Unfurnished": 0, "Semi-Furnished": 1, "Furnished": 2}).values

print(Y)

[10000 20000 17000 ... 35000 45000 15000]


In [5]:
Y = np.asmatrix(Y)
print(Y)
Y = np.transpose(Y)
print(Y)

[[10000 20000 17000 ... 35000 45000 15000]]
[[10000]
 [20000]
 [17000]
 ...
 [35000]
 [45000]
 [15000]]


In [7]:
X = []
m = len(X1)
for i in range(m):
  temp_lst = []
  temp_lst.append(1)
  temp_lst.append(X1[i])
  temp_lst.append(X2[i])
  temp_lst.append(X3[i])
  temp_lst.append(X4[i])
  temp_lst.append(X5[i])
  X.append(temp_lst)

X = np.asmatrix(X)
print(X)

[[   1 1100    2    5    2    0]
 [   1  800    2    5    1    1]
 [   1 1000    2    5    1    1]
 ...
 [   1 1750    3    4    3    1]
 [   1 1500    3    4    2    1]
 [   1 1000    2    4    2    0]]


In [8]:
XT = np.transpose(X)
XTX = np.matmul(XT,X)

from numpy.linalg import inv
INV_XTX = inv(XTX)

XTY = np.matmul(XT,Y)

thetas = np.matmul(INV_XTX,XTY)
print(len(thetas),len(thetas[0]))
print(thetas)

6 1
[[-6.82723281e+04]
 [ 3.04611119e+01]
 [-1.14615583e+03]
 [ 8.66070487e+03]
 [ 2.07343616e+04]
 [ 7.20533636e+03]]


In [9]:
new_thetas = []
t0 = thetas[0][0]
t1 = thetas[1][0]
t2 = thetas[2][0]
t3 = thetas[3][0]
t4 = thetas[4][0]
print(t0,t1,t2,t3,t4)

new_thetas.append(t0)
new_thetas.append(t1)
new_thetas.append(t2)
new_thetas.append(t3)
new_thetas.append(t4)
print("new thetas", new_thetas)

[[-68272.32808883]] [[30.46111189]] [[-1146.15582867]] [[8660.70486794]] [[20734.36156146]]
new thetas [matrix([[-68272.32808883]]), matrix([[30.46111189]]), matrix([[-1146.15582867]]), matrix([[8660.70486794]]), matrix([[20734.36156146]])]


In [10]:
m = len(X1)
sum = 0
for j in range(m):
    tsum = t0 +  t1*X1[j] + t2*X2[j] + t3*X3[j] + t4*X4[j] - Y[j]
    tsum = tsum * tsum
    sum = sum + tsum
    
cost = sum/(2*m)

prediction = t0 + t1*1100 + t2*2 + t3*2 + t4*1

print('cost: ', cost)
print('prediction: ', prediction)

cost:  [[2.30733681e+09]]
prediction:  [[998.35462511]]
